create database COP4331;
use COP4331;

/* Create Users Table*/
CREATE TABLE `COP4331`.`Users` 
( 
  `ID` INT NOT NULL AUTO_INCREMENT , 
    `DateCreated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP , 
    `DateLastLoggedIn` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP , 
    `FirstName` VARCHAR(50) NOT NULL DEFAULT '' , 
    `LastName` VARCHAR(50) NOT NULL DEFAULT '' ,
    `Login` VARCHAR(50) NOT NULL DEFAULT '' , 
    `Password` VARCHAR(50) NOT NULL DEFAULT '' , 
    PRIMARY KEY (`ID`)
) ENGINE = InnoDB;

/* Create Contacts table*/
CREATE TABLE `COP4331`.`Contacts` 
( 
  `ID` INT NOT NULL AUTO_INCREMENT , 
  `FirstName` VARCHAR(50) NOT NULL DEFAULT '' , 
  `LastName` VARCHAR(50) NOT NULL DEFAULT '' ,
  `EMail` VARCHAR(50) NOT NULL DEFAULT '' ,
  `Phone` VARCHAR(10) NOT NULL DEFAULT '', 
  `UserID` INT NOT NULL DEFAULT '0' , 
  PRIMARY KEY (`ID`)
) ENGINE = InnoDB;
